# Generated by Django 5.2.14 on 2026-05-29 23:27

import django.db.models.deletion
import noctua.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('inputs', models.JSONField(default=dict)),
                ('success_criteria', models.TextField(blank=True)),
                ('domain', models.CharField(choices=[('code', 'code'), ('social', 'social'), ('clinical', 'clinical'), ('diagnostic', 'diagnostic'), ('cad', 'cad')], default='code', max_length=32)),
                ('producer_key', models.CharField(max_length=64)),
                ('repo_url', models.TextField(blank=True)),
                ('issue_url', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('stopped', 'stopped'), ('needs_input', 'needs_input')], default='queued', max_length=32)),
                ('state_reason', models.TextField(blank=True)),
                ('budget', models.JSONField(default=dict)),
                ('spent', models.JSONField(default=noctua.core.models.empty_spent)),
                ('needs_input_prompt', models.TextField(blank=True, null=True)),
                ('needs_input_response', models.TextField(blank=True, null=True)),
                ('auto_act', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('pr', 'pr'), ('social_post', 'social_post'), ('analysis', 'analysis'), ('diagnostic', 'diagnostic'), ('cad', 'cad'), ('tool', 'tool')], max_length=32)),
                ('rubric_md', models.TextField(blank=True)),
                ('default_budget', models.JSONField(default=dict)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SandboxRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ref', models.CharField(max_length=512)),
                ('container_id', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(choices=[('booting', 'booting'), ('ready', 'ready'), ('exited', 'exited'), ('torn_down', 'torn_down')], default='booting', max_length=32)),
                ('log_path', models.TextField(blank=True)),
                ('ttl_seconds', models.IntegerField(default=1800)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandboxes', to='core.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('signature', models.JSONField(default=dict)),
                ('source_path', models.TextField()),
                ('source_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('hardcoded', 'hardcoded'), ('fabricated_sandbox_only', 'fabricated_sandbox_only'), ('graduated', 'graduated')], default='hardcoded', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabricated_by_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabricated_tools', to='core.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_key', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('pr', 'pr'), ('social_post', 'social_post'), ('analysis', 'analysis'), ('diagnostic', 'diagnostic'), ('cad', 'cad'), ('tool', 'tool')], max_length=32)),
                ('uri', models.TextField()),
                ('preview', models.JSONField(default=dict)),
                ('provenance', models.JSONField(default=dict)),
                ('validation', models.JSONField(default=dict)),
                ('queue_state', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('promoted', 'promoted')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.mission')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('steps', models.JSONField(default=list)),
                ('rendered_md', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.mission')),
            ],
            options={
                'unique_together': {('mission', 'version')},
            },
        ),
    ]
