# Generated by Django 5.2.14 on 2026-05-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='kind',
            field=models.CharField(choices=[('pr', 'pr'), ('social_post', 'social_post'), ('analysis', 'analysis'), ('diagnostic', 'diagnostic'), ('cad', 'cad'), ('tool', 'tool')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='queue_state',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('promoted', 'promoted')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='mission',
            name='state',
            field=models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('stopped', 'stopped'), ('needs_input', 'needs_input')], db_index=True, default='queued', max_length=32),
        ),
    ]
