# Generated by Django 5.2.14 on 2026-05-30 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_query_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sentry', 'sentry'), ('manual', 'manual')], max_length=32)),
                ('external_id', models.CharField(max_length=256)),
                ('title', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('routing_status', models.CharField(choices=[('pending', 'pending'), ('routed', 'routed'), ('ignored', 'ignored'), ('failed', 'failed')], db_index=True, default='pending', max_length=32)),
                ('routing_reason', models.TextField(blank=True)),
                ('mission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal', to='core.mission')),
            ],
            options={
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
