# Generated by Django 5.2.14 on 2026-05-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_signals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolkit', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('expired', 'expired'), ('revoked', 'revoked'), ('pending', 'pending')], default='pending', max_length=16)),
                ('composio_conn_id', models.CharField(max_length=128)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
