# Generated by Django 5.2.14 on 2026-05-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='source',
            field=models.CharField(choices=[('sentry', 'sentry'), ('manual', 'manual'), ('mock', 'mock')], max_length=32),
        ),
    ]
