# Generated by Django 5.2.14 on 2026-05-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_signal_whatsapp_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='source',
            field=models.CharField(choices=[('sentry', 'sentry'), ('manual', 'manual'), ('mock', 'mock'), ('whatsapp', 'whatsapp'), ('feature_request', 'feature_request')], max_length=32),
        ),
    ]
