# Generated by Django 5.2.14 on 2026-05-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_signal_feature_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='auth_config_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
